datasource:
    url: jdbc:mysql://localhost:3306/iclass?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: zht1741105
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 2
    max-active: 10
    max-wait: 60000